version: '3'

services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=1g
        -Dspark.rdd.compress=true
        -Dspark.serializer=org.apache.spark.serializer.KryoSerializer
        -Dspark.kryo.registrator=org.zouzias.spark.lucenerdd.LuceneRDDKryoRegistrator
        -Dspark.driver.extraJavaOptions=-Dlucenerdd.index.store.mode=disk
        -Dspark.executor.extraJavaOptions=-Dlucenerdd.index.store.mode=disk
      MASTER: local[*]
    ports:
      - 8080:8080
    volumes:
      - ./data:/zeppelin/data
      - ./notebooks:/zeppelin/notebook
      - ./zeppelin-logs:/zeppelin/logs
      - ./zeppelin-run:/zeppelin/run
